apiVersion: v1
kind: Namespace
metadata:
  name: dotnet-project-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddotnet-app-deployment
  namespace: dotnet-project-ns
spec:
  selector:
    matchLabels:
      app: dotnet-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
    containers:
      - name: dotnet-app-container
        image: agpocacr.azurecr.io/dotnetdockerfile:#{Build.BuildId}#
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-svc
  namespace: dotnet-project-ns
  labels:
    service: dotnet-app-svc
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
